### ISSUE TITLE
Mídia

### ISSUE THREAD

**Issue by frontfabi** [perifacode/site#29]
Sessão mídia, com logos dos parceiros em carousel

**Comment by gitlherme** [comment]
**Reutilizar componentes que já foram criados**

## Mobile
![image](https://user-images.githubusercontent.com/37789845/129253227-14b30ba4-0172-4f68-abb6-8344459c6d23.png)


## Desktop
![image](https://user-images.githubusercontent.com/37789845/129253153-9e957d6b-29b8-4c03-9c95-a5c379beb540.png)
