### ISSUE TITLE
Organizadores

### ISSUE THREAD

**Issue by frontfabi** [perifacode/site#30]
Sessão de Organizadores, com título e carousel (contendo foto, nome e @)

**Comment by gitlherme** [comment]
**Mobile**
![image](https://user-images.githubusercontent.com/37789845/129252576-94bdf1d8-dbfd-45c4-882d-5bc34fc9c4af.png)

**Desktop**
![image](https://user-images.githubusercontent.com/37789845/129252624-5825c37d-3d0c-4d2f-81f9-9f6a3ae9a420.png)
