### ISSUE TITLE
Gitflow

### ISSUE THREAD

**Issue by luisangelorjr** [perifacode/site#32]
Oi!

@frontfabi ,estou baixnado o projeto aqui (já mergeei com a develop a new-site)

Vou tentar aplicar o conceito de gitflow no que eu for criando, mas por enquanto sem restrição de pl ou algo assim

- master
- develop
- feature/
- bugfix/
- hotfix/

Isso acima é o conceito de gitflow.
Abri a issue só pra deixar aqui até ele ser totalmente implementado e etc

**Comment by gitlherme** [comment]
@luisangelorjr estou continuando essa tarefa. junto disso, vou criar um lint para commit para manter o padrão.

O padrão deve seguir o Conventional Commits do Angular. (https://www.conventionalcommits.org/en/v1.0.0/)

Além disso, vou colocar para as branchs que não sejam develop e master (que será renomeada pra main) para serem deletadas após o merge delas, assim manter o repositório limpo.

Colocarei isso no README do projeto também =)

**Comment by gabrieldejesus** [comment]
Hello @gitlherme I look forward to the new updates I would love to contribute to the project
