### ISSUE TITLE
Accept one more on the team?

### ISSUE THREAD

**Issue by gabrieldejesus** [perifacode/site#37]
Hello team from the perifacode, if you are interested, I would like to contribute to the project. If so, could you provide me with the app layout?

**Comment by gitlherme** [comment]
@gabrieldejesus foi mal a demora por tanto tempo, com essa pandemia, demos uma parada.

O projeto vai ter uma reformulação e por isso, estou fechando essa issue.

Toda contribuição será bem vinda, logo logo deixarei no README do projeto como contribuir =)

**Comment by gabrieldejesus** [comment]
Hello @gitlherme I look forward to the new updates I would love to contribute to the project

**Comment by gitlherme** [comment]
Todas as atualizações estarão na branch 'main', @gabrieldejesus.

O projeto será em Nuxt, estou configurando tudo certinho para podermos começar!

Deixarei no README todo o processo para colaboração. Quando o README estiver finalizado, te menciono por aqui =)

**Comment by gabrieldejesus** [comment]
Thank you @gitlherme ✨

**Comment by gitlherme** [comment]
@gabrieldejesus acho que está tudo configurado para recebermos contribuição! Caso voce queira puxar alguma tarefa do board para fazer, fique a vontade! Vou atualizar a branch de develop para receber as contribuicoes, só criar o PR para ela quando terminar =)

Lembre-se de dar uma olhadinha no README para entender os padrões e muito obrigado por demonstrar interesse 💛
