### ISSUE TITLE
Link de entrada para o Telegram

### ISSUE THREAD

**Issue by luisangelorjr** [perifacode/site#4]
Uma reclamação recorrente do pessoal tem sido o link de entrada para o grupo

Acabei de revisitar a page (de um notebook) e pra mim está suave encontrar o link.
Mas queria propor a discussão aqui para entendermos se é melhor alterar isso ou não.

**Comment by frontfabi** [comment]
Pega as opções sugeridas pela galera e faz um teste A/B

**Comment by frontfabi** [comment]
A minha sugestão é fazer um CTA do link de convite

**Comment by gitlherme** [comment]
O que eu entendi da galera é que o problema não é achar o link em si, e sim ter que passar por todo aquele processo de responder formulário, entrar no grupo, colocar código do bot.

Sinceramente eu acho desse jeito está bem confiável, mas tenho certeza que dá pra melhorar o UX de tudo isso.

**Comment by frontfabi** [comment]
Concordo q o processo está bem confiável e tbm n mexeria. Só essa alteraçãozinha besta em UX mesmo!
